### ISSUE TITLE
unpack skip fails for multi-byte values after TypeError

### ISSUE THREAD

**Issue by KenMacD** [msgpack/msgpack-python#148]
When attempting to skip and item after the unpack has failed the resulting skip will raise and exception if the map item is longer than one byte.

In the test cases below you can see that the skip works fine with the one byte value, but fails with a multi-byte value. The unpack exceptions are expected. 

Good Test Case `\x81\x92BC\xcc\xff`:

```
>>> p = Unpacker(BytesIO(dumps({(66,67): 0xff})))
>>> p.unpack()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "msgpack/_unpacker.pyx", line 427, in msgpack._unpacker.Unpacker.unpack (msgpack/_unpacker.cpp:4834)
  File "msgpack/_unpacker.pyx", line 390, in msgpack._unpacker.Unpacker._unpack (msgpack/_unpacker.cpp:4268)
TypeError: unhashable type: 'list'
>>> p.skip()
>>>
```

Failed Test Case `\x81\x92BC\xcd\xff\xff`:
```
>>> p = Unpacker(BytesIO(dumps({(66,67): 0xffff})))
>>> p.unpack()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "msgpack/_unpacker.pyx", line 427, in msgpack._unpacker.Unpacker.unpack (msgpack/_unpacker.cpp:4834)
  File "msgpack/_unpacker.pyx", line 390, in msgpack._unpacker.Unpacker._unpack (msgpack/_unpacker.cpp:4268)
TypeError: unhashable type: 'list'
>>> p.skip()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "msgpack/_unpacker.pyx", line 437, in msgpack._unpacker.Unpacker.skip (msgpack/_unpacker.cpp:4942)
  File "msgpack/_unpacker.pyx", line 405, in msgpack._unpacker.Unpacker._unpack (msgpack/_unpacker.cpp:4477)
msgpack.exceptions.OutOfData: No more data to unpack.

```

**Comment by KenMacD** [comment]
I've also tested this by passing a callback in to `skip()`. In the good case the result is the function is called once, and passed 1 byte of data.

In the bad case the function is called twice, and in both cases `len(data)` is 0.

**Comment by KenMacD** [comment]
I did some printing of the offset in the callback:

Good:
```
OFF: 6
LEN: 1
```

Bad:
```
OFF: 6
LEN: 0
OFF: 6
LEN: 0
```

which is a little strange as the second buffer should be larger (aside from the fact that it's called twice and neither version receives the actual data)

**Comment by methane** [comment]
I don't intend to use `.skip()` after `unpack()` error.
Does your `p.skip()` succeeds without `p.unpack()`?

**Comment by KenMacD** [comment]
Yes, skipping over them works fine, as it does in the good case.

**Comment by methane** [comment]
After error other than OutOfData is raised, the unpacker is unstable state.
All methods may not work.  It's by design.

**Comment by KenMacD** [comment]
Well in that case it seems like it would make sense to track when one of these exceptions has been returned and fail early in any subsequent calls on that object. Otherwise the user has an object in an 'unstable state' that also sometimes works fine, which is a great place for bugs to hide.
