### ISSUE TITLE
UnicodeEncodeError while dumping unicode string in python 3.4

### ISSUE THREAD

**Issue by saeedsq** [msgpack/msgpack-python#175]
import msgpack
    msgpack.dumps({"json": u"\ud83d\ude02"})

Error:

    ..../python3.4/site-packages/msgpack/__init__.py", line 47, in packb
        return Packer(**kwargs).pack(o)
      File "msgpack/_packer.pyx", line 231, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:231)
      File "msgpack/_packer.pyx", line 233, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:233)
      File "msgpack/_packer.pyx", line 192, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:192)
      File "msgpack/_packer.pyx", line 174, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:174)
    UnicodeEncodeError: 'utf-8' codec can't encode character '\ud83d' in position 0: surrogates not allowed

**Comment by methane** [comment]
It's not a bug.  Your unicode is broken.
```
>>> u"\ud83d\ude02".encode('utf-8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'utf-8' codec can't encode character '\ud83d' in position 0: surrogates not allowed
```

**Comment by methane** [comment]
FYI
```
In [4]: msgpack.packb(u"\ud83d\ude02", unicode_errors='surrogatepass')
Out[4]: b'\xa6\xed\xa0\xbd\xed\xb8\x82'
```

But I think you shouldn't produce data containing invalid utf-8.

**Comment by saeedsq** [comment]
This unicode is used for emoticons. I just wanted to make sure this isn't a unicode error in your pickling.

**Comment by methane** [comment]
I don't know how you got the unicode.  But you failed to decode some data properly.
Surrogate pairs should be merged while decoding.

```py
>>> import json
>>> json.loads('"\\ud83d\\ude02"')
'😂'
>>> len(_)
1
>>> json.loads('"\\ud83d\\ude02"').encode('utf-8')
b'\xf0\x9f\x98\x82'
```
