### ISSUE TITLE
PackValueError: Integer value out of range (pure python msgpack)

### ISSUE THREAD

**Issue by ThomasWaldmann** [msgpack/msgpack-python#221]
Just got this feedback from a borgbackup user:

```
Enter Password:
Using a pure-python msgpack! This will result in lower performance.
Local Exception.10 GB C 237.68 MB D 35981 N cygdrive/*****
Traceback (most recent call last):
  File "/home/Zoom/borg/src/borg/archiver.py", line 3434, in main
    exit_code = archiver.run(args)
  File "/home/Zoom/borg/src/borg/archiver.py", line 3362, in run
    return func(args)
  File "/home/Zoom/borg/src/borg/archiver.py", line 116, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/home/Zoom/borg/src/borg/archiver.py", line 475, in do_create
    create_inner(archive, cache)
  File "/home/Zoom/borg/src/borg/archiver.py", line 439, in create_inner
    read_special=args.read_special, dry_run=dry_run, st=st)
  File "/home/Zoom/borg/src/borg/archiver.py", line 532, in _process
    read_special=read_special, dry_run=dry_run)
  File "/home/Zoom/borg/src/borg/archiver.py", line 532, in _process
    read_special=read_special, dry_run=dry_run)
  File "/home/Zoom/borg/src/borg/archiver.py", line 532, in _process
    read_special=read_special, dry_run=dry_run)
  File "/home/Zoom/borg/src/borg/archiver.py", line 532, in _process
    read_special=read_special, dry_run=dry_run)
  File "/home/Zoom/borg/src/borg/archiver.py", line 532, in _process
    read_special=read_special, dry_run=dry_run)
  File "/home/Zoom/borg/src/borg/archiver.py", line 511, in _process
    status = archive.process_file(path, st, cache, self.ignore_inode)
  File "/home/Zoom/borg/src/borg/archive.py", line 951, in process_file
    cache.memorize_file(path_hash, st, [c.id for c in item.chunks])
  File "/home/Zoom/borg/src/borg/cache.py", line 594, in memorize_file
    self.files[path_hash] = msgpack.packb(entry)
  File "/home/Zoom/borg-env/lib/python3.4/site-packages/msgpack/__init__.py", line 47, in packb
    return Packer(**kwargs).pack(o)
  File "/home/Zoom/borg-env/lib/python3.4/site-packages/msgpack/fallback.py", line 738, in pack
    self._pack(obj)
  File "/home/Zoom/borg-env/lib/python3.4/site-packages/msgpack/fallback.py", line 726, in _pack
    self._pack(obj[i], nest_limit - 1)
  File "/home/Zoom/borg-env/lib/python3.4/site-packages/msgpack/fallback.py", line 662, in _pack
    raise PackValueError("Integer value out of range")
msgpack.exceptions.PackValueError: Integer value out of range

Platform: CYGWIN_NT-6.1 workstation 2.6.1(0.305/5/3) 2016-12-16 11:55 x86_64
Borg: 1.1.0b4.dev174+ngec1304b  Python: CPython 3.4.3
PID: 5836  CWD: /home/Zoom
sys.argv: ['/home/Zoom/borg-env/bin/borg', 'create', '-v', '--stats', '--progress', '--compression', 'zlib,3', '/cygdrive/*****', '/cygdrive/*****', '--exclude-from', 'exclude.ls', '--compression-from', 'compression.conf']
```

**Comment by ThomasWaldmann** [comment]
It looks like borg was installed into a virtualenv ("borg-env"), so I'ld suspect msgpack is the latest from pypi.

As windows and cygwin was being used (and the necessary build dependencies not installed), it did not compile the msgpack C implementation and thus used the slow pure-python implementation.

Python integers are unlimited (but maybe msgpack serializable ints aren't?). It would have been useful if it had included the value of the problematic int in the exception message.

The "entry" serialized here contains mtime_ns, inode number, size of filesystem file (or other item). I've never seen that exception before...

**Comment by enkore** [comment]
Perhaps a bad mtime_ns -> larger than 64 bits somehow?

**Comment by methane** [comment]
>  (but maybe msgpack serializable ints aren't?).

Yes. Like JSON, there are limitation. See the spec.

**Comment by ThomasWaldmann** [comment]
I've looked at the 0.4.8 release code and it looks like this exception is only thrown if:
- the integer is bigger than MAX_UINT64 (> 0xffffffffffffffff)
- the integer is less than MIN_INT64 (< -0x8000000000000000)

So, how can that be? Do we have a OS interface that gives us more than 64bits?

**Comment by jfolz** [comment]
Python uses arbitrary precision integers, so `1000**1000` works find. The only limit is memory. So any processing can result in numbers >64 bits.

**Comment by ThomasWaldmann** [comment]
@jfolz sure, that is known. but we have just values from os.stat there: inode, mtime_ns and (file) size.

**Comment by ThomasWaldmann** [comment]
11:13  ZoomZoomZoom$ Hey, by the way, I've looked into file properties, and the creation and modification time is September, 6th 2569

```
>>> datetime.datetime(2569, 9, 6) - datetime.datetime(1970, 1, 1)
datetime.timedelta(219029)
>>> 219029*24*3600 * 1e9 > 2**64
True
```

**Comment by ThomasWaldmann** [comment]
Closing this, not msgpack's fault.
