### ISSUE TITLE
Decoding fails for readonly buffer.

### ISSUE THREAD

**Issue by gsuyashs** [msgpack/msgpack-python#254]
```
>>> import msgpack
>>> msgpack.version
(0, 4, 8)
>>> msgpack.dumps(buffer("suyash",0,3))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/msgpack/__init__.py", line 47, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 231, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:3661)
  File "msgpack/_packer.pyx", line 233, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:3503)
  File "msgpack/_packer.pyx", line 228, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:3382)
TypeError: can't serialize <read-only buffer for 0x6ffffdeeb40, size 3, offset 0 at 0x6ffffdf00f0>
```

In case of python native (de)serialization module ``marshal`` works fine with ``buffer``
```
>>> import marshal
>>> marshal.dumps(buffer("suyash",0,-1))
's\x06\x00\x00\x00suyash'
>>>
>>> marshal.loads(_)
'suyash'
>>>
```

**Comment by jfolz** [comment]
Git master supports packing `memoryview` objects.
`buffer` uses a deprecated API.

**Comment by methane** [comment]
released.
