### ISSUE TITLE
Updating from msgpack-python from 0.4.2 to 0.5.0 produces a unusable library

### ISSUE THREAD

**Issue by vEpiphyte** [msgpack/msgpack-python#266]
Installing msgpack-python 0.5.0 from pip produces a non-working msgpack installation.
It appears the installation of msgpack=0.5.0 from msgpack-python 0.5.0 isn't actually installing msgpack.
Installing msgpack==0.5.0 works fine.

Steps to reproduce (using pyenv):
```
pyenv virtualenv --copies 3.6.1 msgpack_test
pyenv shell msgpack_test
python -m pip install msgpack-python==0.4.2
python -m pip install msgpack-python==0.5.0
```

Importing msgpack then fails
```
python -c "import msgpack"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'msgpack'``
```

Checking the site packages directory between package installations shows the msgpack package 
 code is disspearing
```

(msgpack_test) someuser@someplace:~$ ls ~/.pyenv/versions/msgpack_test/lib/python3.6/site-packages/msgpack*
/home/someuser/.pyenv/versions/msgpack_test/lib/python3.6/site-packages/msgpack:
exceptions.py  fallback.py  __init__.py  _packer.cpython-36m-x86_64-linux-gnu.so  __pycache__  _unpacker.cpython-36m-x86_64-linux-gnu.so  _version.py

/home/someuser/.pyenv/versions/msgpack_test/lib/python3.6/site-packages/msgpack_python-0.4.2.dist-info:
DESCRIPTION.rst  INSTALLER  METADATA  metadata.json  RECORD  top_level.txt  WHEEL

(msgpack_test) someuser@someplace:~$ python -m pip install msgpack-python==0.5.0
Collecting msgpack-python==0.5.0
  Using cached msgpack_python-0.5.0-py3-none-any.whl
Collecting msgpack>=0.5 (from msgpack-python==0.5.0)
Installing collected packages: msgpack, msgpack-python
  Found existing installation: msgpack-python 0.4.2
    Uninstalling msgpack-python-0.4.2:
      Successfully uninstalled msgpack-python-0.4.2
Successfully installed msgpack-0.5.0 msgpack-python-0.5.0

(msgpack_test) someuser@someplace:~$ ls ~/.pyenv/versions/msgpack_test/lib/python3.6/site-packages/msgpack*
/home/someuser/.pyenv/versions/msgpack_test/lib/python3.6/site-packages/msgpack-0.5.0.dist-info:
DESCRIPTION.rst  INSTALLER  METADATA  metadata.json  RECORD  top_level.txt  WHEEL

/home/someuser/.pyenv/versions/msgpack_test/lib/python3.6/site-packages/msgpack_python-0.5.0.dist-info:
DESCRIPTION.rst  INSTALLER  METADATA  metadata.json  RECORD  top_level.txt  WHEEL


(msgpack_test) someuser@someplace:~$ ls ~/.pyenv/versions/msgpack_test/lib/python3.6/site-packages/msgpack*
/home/someuser/.pyenv/versions/msgpack_test/lib/python3.6/site-packages/msgpack-0.5.0.dist-info:
DESCRIPTION.rst  INSTALLER  METADATA  metadata.json  RECORD  top_level.txt  WHEEL

/home/someuser/.pyenv/versions/msgpack_test/lib/python3.6/site-packages/msgpack_python-0.5.0.dist-info:
DESCRIPTION.rst  INSTALLER  METADATA  metadata.json  RECORD  top_level.txt  WHEEL
```

Pip is using version 9.0.1.

**Comment by vertexmc** [comment]
I am able to reproduce this issue.

**Comment by methane** [comment]
pip install msgpack-python does:

* Install msgpack (overwrite msgpack package)
* Uninstall msgpack-python (remove new msgpack package)

I'm sorry but there are nothing I can do about it.
`uritemplate.py` has same issue.  Maybe, pip behavior was changed sometime.

```
$ pip install uritemplate.py==2.0
Collecting uritemplate.py==2.0
  Downloading uritemplate.py-2.0.0.tar.gz
Installing collected packages: uritemplate.py
  Running setup.py install for uritemplate.py ... done
Successfully installed uritemplate.py-2.0.0

$ pip install -U uritemplate.py
Collecting uritemplate.py
  Downloading uritemplate.py-3.0.2-py2.py3-none-any.whl
Collecting uritemplate>=2.0 (from uritemplate.py)
  Downloading uritemplate-3.0.0-py2.py3-none-any.whl
Installing collected packages: uritemplate, uritemplate.py
  Found existing installation: uritemplate.py 2.0.0
    Uninstalling uritemplate.py-2.0.0:
      Successfully uninstalled uritemplate.py-2.0.0
Successfully installed uritemplate-3.0.0 uritemplate.py-3.0.2

$ python -c 'import uritemplate'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'uritemplate'
```

**Comment by vEpiphyte** [comment]
Probably caused by pypa/pip#4961
