### ISSUE TITLE
TypeError on Python 2.7.3, as seen with pip 10 on debian wheezy

### ISSUE THREAD

**Issue by alex** [msgpack/msgpack-python#299]
```
Exception:
Traceback (most recent call last):
  File "/var/jenkins_home/workspace/3610-6MJAZQSTTEPICPG/cryptography/.tox/py27/local/lib/python2.7/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/var/jenkins_home/workspace/3610-6MJAZQSTTEPICPG/cryptography/.tox/py27/local/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 291, in run
    resolver.resolve(requirement_set)
  File "/var/jenkins_home/workspace/3610-6MJAZQSTTEPICPG/cryptography/.tox/py27/local/lib/python2.7/site-packages/pip/_internal/resolve.py", line 103, in resolve
    self._resolve_one(requirement_set, req)
  File "/var/jenkins_home/workspace/3610-6MJAZQSTTEPICPG/cryptography/.tox/py27/local/lib/python2.7/site-packages/pip/_internal/resolve.py", line 257, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/var/jenkins_home/workspace/3610-6MJAZQSTTEPICPG/cryptography/.tox/py27/local/lib/python2.7/site-packages/pip/_internal/resolve.py", line 210, in _get_abstract_dist_for
    self.require_hashes
  File "/var/jenkins_home/workspace/3610-6MJAZQSTTEPICPG/cryptography/.tox/py27/local/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 243, in prepare_linked_requirement
    req.populate_link(finder, upgrade_allowed, require_hashes)
  File "/var/jenkins_home/workspace/3610-6MJAZQSTTEPICPG/cryptography/.tox/py27/local/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 307, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/var/jenkins_home/workspace/3610-6MJAZQSTTEPICPG/cryptography/.tox/py27/local/lib/python2.7/site-packages/pip/_internal/index.py", line 484, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/var/jenkins_home/workspace/3610-6MJAZQSTTEPICPG/cryptography/.tox/py27/local/lib/python2.7/site-packages/pip/_internal/index.py", line 442, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/var/jenkins_home/workspace/3610-6MJAZQSTTEPICPG/cryptography/.tox/py27/local/lib/python2.7/site-packages/pip/_internal/index.py", line 587, in _get_pages
    page = self._get_page(location)
  File "/var/jenkins_home/workspace/3610-6MJAZQSTTEPICPG/cryptography/.tox/py27/local/lib/python2.7/site-packages/pip/_internal/index.py", line 705, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/var/jenkins_home/workspace/3610-6MJAZQSTTEPICPG/cryptography/.tox/py27/local/lib/python2.7/site-packages/pip/_internal/index.py", line 814, in get_page
    "Cache-Control": "max-age=600",
  File "/var/jenkins_home/workspace/3610-6MJAZQSTTEPICPG/cryptography/.tox/py27/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/var/jenkins_home/workspace/3610-6MJAZQSTTEPICPG/cryptography/.tox/py27/local/lib/python2.7/site-packages/pip/_internal/download.py", line 397, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/var/jenkins_home/workspace/3610-6MJAZQSTTEPICPG/cryptography/.tox/py27/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/jenkins_home/workspace/3610-6MJAZQSTTEPICPG/cryptography/.tox/py27/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/var/jenkins_home/workspace/3610-6MJAZQSTTEPICPG/cryptography/.tox/py27/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 42, in send
    cached_response = self.controller.cached_request(request)
  File "/var/jenkins_home/workspace/3610-6MJAZQSTTEPICPG/cryptography/.tox/py27/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/controller.py", line 137, in cached_request
    resp = self.serializer.loads(request, cache_data)
  File "/var/jenkins_home/workspace/3610-6MJAZQSTTEPICPG/cryptography/.tox/py27/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 98, in loads
    return getattr(self, "_loads_v{0}".format(ver))(request, data)
  File "/var/jenkins_home/workspace/3610-6MJAZQSTTEPICPG/cryptography/.tox/py27/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 190, in _loads_v4
    cached = msgpack.loads(data, encoding='utf-8')
  File "/var/jenkins_home/workspace/3610-6MJAZQSTTEPICPG/cryptography/.tox/py27/local/lib/python2.7/site-packages/pip/_vendor/msgpack/fallback.py", line 121, in unpackb
    ret = unpacker._unpack()
  File "/var/jenkins_home/workspace/3610-6MJAZQSTTEPICPG/cryptography/.tox/py27/local/lib/python2.7/site-packages/pip/_vendor/msgpack/fallback.py", line 600, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "/var/jenkins_home/workspace/3610-6MJAZQSTTEPICPG/cryptography/.tox/py27/local/lib/python2.7/site-packages/pip/_vendor/msgpack/fallback.py", line 600, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "/var/jenkins_home/workspace/3610-6MJAZQSTTEPICPG/cryptography/.tox/py27/local/lib/python2.7/site-packages/pip/_vendor/msgpack/fallback.py", line 560, in _unpack
    typ, n, obj = self._read_header(execute)
  File "/var/jenkins_home/workspace/3610-6MJAZQSTTEPICPG/cryptography/.tox/py27/local/lib/python2.7/site-packages/pip/_vendor/msgpack/fallback.py", line 391, in _read_header
    n = struct.unpack_from(">H", self._buffer, self._buff_i)[0]
TypeError: unpack_from() argument 1 must be string or read-only buffer, not bytearray
```

**Comment by jfolz** [comment]
Just tested, this was fixed between 2.7.3 and 2.7.14, where `unpack_from` supports `bytearray`.

**Comment by alex** [comment]
https://github.com/python/cpython/commit/b8285d96f40a635157b0394f7cf9e69d0e6492cf is when it was added to CPython.

**Comment by alex** [comment]
Looks like that means Python 2.7.10.

**Comment by alex** [comment]
#199 appears to be when the code was introduced

**Comment by alex** [comment]
Fix up in #300

**Comment by methane** [comment]
Generally speaking, "supports 2.7" means "supports recent micro versions of 2.7".
I don't want to add more code to support such old python.

Install new Python is always recommended when you want to install package from PyPI.

Or is you Debian mainteiner and port this fix to Debian's package?

**Comment by alex** [comment]
I'm not a debian maintainer. I'm a maintainer of the pyca/cryptography family of libraries, and we run CI on a lot of different platforms, including wheezy. I figured the least I could do was come up with a patch.

If you have no interest in supporting this, I totally understand, no one hates supporting old crap more than me (the pip that comes out of the box on wheezy is so old that it can't even talk to PyPI...).

I think pip will probably cherry-pick this onto their vendored copy of msgpack either way.

**Comment by methane** [comment]
Fair enough.  Thanks for you report.
