### ISSUE TITLE
Broken fallback implementation of Unpacker.read_bytes

### ISSUE THREAD

**Issue by jmuchemb** [msgpack/msgpack-python#352]
```
>>> from msgpack import *
>>> u = Unpacker(); u.feed('x'); u.read_bytes(1)
'x'
>>> u.next()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "msgpack/_unpacker.pyx", line 562, in msgpack._cmsgpack.Unpacker.__next__
  File "msgpack/_unpacker.pyx", line 489, in msgpack._cmsgpack.Unpacker._unpack
StopIteration: No more data to unpack.
>>> u.feed('\1'); u.next()
1
```
So far so good. Now with fallback implémentation:
```
>>> from msgpack.fallback import *
>>> u = Unpacker(); u.feed('x'); u.read_bytes(1)
bytearray(b'x')
>>> u.next()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/msgpack/fallback.py", line 690, in __next__
    raise StopIteration
StopIteration
>>> u.feed('\1'); u.next()
120
```
Something seems to be wrongly reset on StopIteration.

**Comment by jfolz** [comment]
Can't reproduce with msgpack 0.6.1 and Python 3.6.
```
import msgpack
from msgpack.fallback import Unpacker
print(msgpack.version)
u = Unpacker()
u.feed(b'x')
print(u.read_bytes(1) == b'x')
u.feed(b'\1')
print(u.next() == 1)
```

```
(0, 6, 1)
True
True
```

Maybe a 2.7 thing?

**Comment by jfolz** [comment]
Then, when `next` is called, `_buff_i` is set to `_buf_checkpoint` which is still 0 [here](https://github.com/msgpack/msgpack-python/blob/381c2eff5f8ee0b8669fd6daf1fd1ecaffe7c931/msgpack/fallback.py#L379).
That's why you get the first message in the stream and not the second as expected.
