### ISSUE TITLE
[1.0.0] Loading fails for dictionary that have tuple of tuples as keys

### ISSUE THREAD

**Issue by lucventurini** [msgpack/msgpack-python#412]
To reproduce:

```
>>> msgpack.loads(msgpack.dumps({((10, 20), (20, 30)): 10}))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
ValueError: list is not allowed for map key
```

Is there any workaround for this?

**Comment by methane** [comment]
Read the readme.
