### ISSUE TITLE
Does not work with all msgpack

### ISSUE THREAD

**Issue by quentin-sommer** [msgpack/msgpack-python#496]
I use [msgpackr](https://github.com/kriszyp/msgpackr) in node to produce my messages. I use the [record option](https://github.com/kriszyp/msgpackr#record--object-structures) to achieve smaller messages. This library fails to decode those messages when the records option is activated, but works fine when it is disabled.

I compared with the python `umsgpack` library and it is able to parse messages from `msgpackr`.
Reproduction:

```js
// Js part
const { Packr} = require('msgpackr')
const packr = new Packr({useRecords: true})

packr.pack({}).toString('base64') // '1HJAkA=='
```
Then decoding from python:
```py
# Python part

import msgpack
import umsgpack
import base64

b64 = '1HJAkA=='

# Traceback (most recent call last):
#   File "read_extension.py", line 14, in <module>
#     msgpack.unpackb(base64.b64decode(b64))
#   File "msgpack/_unpacker.pyx", line 201, in msgpack._cmsgpack.unpackb
# msgpack.exceptions.ExtraData: unpack(b) received extra data.
msgpack.unpackb(base64.b64decode(b64))

# But this works
umsgpack.unpackb(base64.b64decode(b64))
```

I tested some other examples and it seems that it only breaks when an object is serialized:

```
packr.pack(1) OK
packr.pack([1,2,3]) OK
packr.pack([{}]) KO
```

**Comment by methane** [comment]
> msgpack.exceptions.ExtraData: unpack(b) received extra data.

This means your data contains more than one object. You need to stream unpacker.

```
In [3]: data = base64.b64decode('1HJAkA==')

In [4]: data
Out[4]: b'\xd4r@\x90'

In [5]: up=msgpack.Unpacker()

In [6]: up.feed(data)

In [7]: next(up)
Out[7]: ExtType(code=114, data=b'@')

In [8]: next(up)
Out[8]: []

In [9]: next(up)
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
```

**Comment by quentin-sommer** [comment]
Hi, thanks for the answer!
Indeed now it seems to unpack it correctly but how can I get a dict/list back?

**Comment by methane** [comment]
I don't know. It's msgpackr's original format extension. You should learn how msgpackr encodes objects and interpret unpacked objects.

**Comment by quentin-sommer** [comment]
Thank you!
