### ISSUE TITLE
Serializing Django's ErrorList results in invalid bytes

### ISSUE THREAD

**Issue by LilyFoote** [msgpack/msgpack-python#574]
I've created a [minimal example](https://github.com/LilyFoote/msgpack-errorlist).

```python
# msgpack_errorlist.tests
from unittest import TestCase

import msgpack
from django.forms.utils import ErrorList


class MsgpackTestCase(TestCase):
    def test_errorlist(self):
        data = ErrorList("T")

        raw = msgpack.packb(data)

        msgpack.unpackb(raw)
```

```
msgpack_errorlist$ python manage.py test
Found 1 test(s).
System check identified no issues (0 silenced).
E
======================================================================
ERROR: test_errorlist (msgpack_errorlist.tests.MsgpackTestCase.test_errorlist)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lily/work/kloppindustries/msgpack_errorlist/msgpack_errorlist/tests.py", line 13, in test_errorlist
    msgpack.unpackb(raw)
  File "msgpack/_unpacker.pyx", line 201, in msgpack._cmsgpack.unpackb
msgpack.exceptions.ExtraData: unpack(b) received extra data.

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

The invalid msgpack bytes are: `\x90\xa1T`.

My unproven suspicion is that this is something to do with [`ErrorList` subclassing `list`](https://github.com/django/django/blob/e67d3580edbee1a4b58d40875293714ac3fc6937/django/forms/utils.py#L141C52-L141C52).

**Comment by LilyFoote** [comment]
Ah! I just discovered the `strict_types` flag!
