### ISSUE TITLE
Failed install on iot venusos system on RaspberryPi 3B+ (ARMv7 r4)

### ISSUE THREAD

**Issue by midnightblock24** [msgpack/msgpack-python#630]
Not enough of a Python programmer to tell what the issue is, but I am guessing it doesn't know what VenusOS is, and can't determine proper environment  settings? TIA

# python -m pip install msgpack
Collecting msgpack
  Using cached msgpack-1.1.0.tar.gz (167 kB)
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/usr/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 515, in prepare_linked_requirement
    abstract_dist = _get_prepared_distribution(
  File "/usr/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 95, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/usr/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 33, in prepare_distribution_metadata
    self.req.load_pyproject_toml()
  File "/usr/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 512, in load_pyproject_toml
    pyproject_toml_data = load_pyproject_toml(
  File "/usr/lib/python3.8/site-packages/pip/_internal/pyproject.py", line 75, in load_pyproject_toml
    pp_toml = pytoml.load(f)
  File "/usr/lib/python3.8/site-packages/pip/_vendor/pytoml/parser.py", line 11, in load
    return loads(fin.read(), translate=translate, object_pairs_hook=object_pairs_hook, filename=getattr(fin, 'name', repr(fin)))
  File "/usr/lib/python3.8/site-packages/pip/_vendor/pytoml/parser.py", line 24, in loads
    ast = _p_toml(src, object_pairs_hook=object_pairs_hook)
  File "/usr/lib/python3.8/site-packages/pip/_vendor/pytoml/parser.py", line 341, in _p_toml
    s.expect_eof()
  File "/usr/lib/python3.8/site-packages/pip/_vendor/pytoml/parser.py", line 123, in expect_eof
    return self._expect(self.consume_eof())
  File "/usr/lib/python3.8/site-packages/pip/_vendor/pytoml/parser.py", line 163, in _expect
    raise TomlError('msg', self._pos[0], self._pos[1], self._filename)
pip._vendor.pytoml.core.TomlError: /var/volatile/tmp/pip-install-n9zfrj97/msgpack/pyproject.toml(47, 1): msg

**Comment by ThomasWaldmann** [comment]
@midnightblock24 Strange.

I just tried installing from the pypi.org msgpack 1.1.0 .tgz file (NOT using a prebuilt wheel) and it worked for me (on macOS, ARM64). I used a much more recent python version though (3.13.1).

The traceback looks like the toml parser is stumbling over something in the `pyproject.toml` file. I had a look, but everything looks ok there. So, is maybe the python 3.8 toml parser buggy?

Can you run the command again, using:
- a more recent python version ?
- pip install -v ... ?

**Comment by midnightblock24** [comment]
updated from pip20 to pip 24

looks llke colorsys is not available... which means the python install is broken, I guess...

# python -m pip install -v msgpack

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/site-packages/pip/__main__.py", line 22, in <module>
    from pip._internal.cli.main import main as _main
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 11, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "/usr/lib/python3.8/site-packages/pip/_internal/build_env.py", line 18, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "/usr/lib/python3.8/site-packages/pip/_internal/utils/logging.py", line 13, in <module>
    from pip._vendor.rich.console import (
  File "/usr/lib/python3.8/site-packages/pip/_vendor/rich/console.py", line 47, in <module>
    from . import errors, themes
  File "/usr/lib/python3.8/site-packages/pip/_vendor/rich/themes.py", line 1, in <module>
    from .default_styles import DEFAULT_STYLES
  File "/usr/lib/python3.8/site-packages/pip/_vendor/rich/default_styles.py", line 3, in <module>
    from .style import Style
  File "/usr/lib/python3.8/site-packages/pip/_vendor/rich/style.py", line 8, in <module>
    from .color import Color, ColorParseError, ColorSystem, blend_rgb
  File "/usr/lib/python3.8/site-packages/pip/_vendor/rich/color.py", line 3, in <module>
    from colorsys import rgb_to_hls
ModuleNotFoundError: No module named 'colorsys'

**Comment by midnightblock24** [comment]
thanks! It's a problem with the Python build on this minimal OS
